var mongoose   = require("mongoose");
// var passportLocalMongoose = require("passport-local-mongoose");

var BufferedOperationDataSchema = new mongoose.Schema({
    siteID                                            : String,
    deviceID                                          : String,
    customerName                                      : String,
    ACMeterWorkingStatus                              : Number, 
    ACcurrenTimeYYMM                                  : Number,
    ACcurrenTimeDDhh                                  : Number,
    ACcurrenTimemmss                                  : Number,                                              
    ACfrequency                                       : Number,       
    ACphaseAVoltage                                   : Number,       
    ACphaseBVoltage                                   : Number,       
    ACphaseCVoltage                                   : Number,       
    ACfirstAphaseCurrent                              : Number,       
    ACfirstBphaseCurrent                              : Number,       
    ACfirstCphaseCurrent                              : Number,    
    ACfirstTotalApparentPower                         : Number,       
    ACfirstApparentPowerPhaseA                        : Number,       
    ACfirstApparentPowerPhaseB                        : Number,       
    ACfirstApparentPowerPhaseC                        : Number,       
    ACfirstTotalActivePower                           : Number,       
    ACfirstActivePowerPhaseA                          : Number,       
    ACfirstActivePowerPhaseB                          : Number,       
    ACfirstActivePowerPhaseC                          : Number,       
    ACfirstTotalReactivePower                         : Number,       
    ACfirstReactivePowerPhaseA                        : Number,       
    ACfirstReactivePowerPhaseB                        : Number,       
    ACfirstReactivePowerPhaseC                        : Number,       
    ACfirstCombinedActiveTotalPower1                  : Number,       
    ACfirstCombinedActiveTotalPower2                  : Number,       
    ACfirstPositiveActiveTotalEnergy1                 : Number,       
    ACfirstPositiveActiveTotalEnergy2                 : Number,       
    ACfirstReverseActivePowerTotalEnergy1             : Number,       
    ACfirstReverseActivePowerTotalEnergy2             : Number,       
    ACfirstCombinedReactivePower1TotalElectricEnergy1 : Number,       
    ACfirstCombinedReactivePower1TotalElectricEnergy2 : Number,       
    ACfirstCombinedReactivePower2TotalElectricEnergy1 : Number,       
    ACfirstCombinedReactivePower2TotalElectricEnergy2 : Number,       
    ACFirstTotalPowerFactor                           : Number,       
    ACFirstAphasePowerFactor                          : Number,       
    ACFirstBphasePowerFactor                          : Number,       
    ACFirstCphasePowerFactor                          : Number,       
    DCvoltage                                         : Number,      
    DCch1Current                                      : Number,      
    DCch1ActivePower                                  : Number,      
    DCch1CombinedActiveEnergy                         : Number,      
    DCch1PositiveActiveEnergy                         : Number,      
    DCch1NegativeActiveEnergy                         : Number,      
    DCch2Current                                      : Number,      
    DCch2ActivePower                                  : Number,      
    DCch2CombinedActiveEnergy                         : Number,      
    DCch2PositiveActiveEnergy                         : Number,      
    DCch2NegativeActiveEnergy                         : Number,      
    DCch3Current                                      : Number,      
    DCch3ActivePower                                  : Number,      
    DCch3CombinedActiveEnergy                         : Number,      
    DCch3PositiveActiveEnergy                         : Number,      
    DCch3NegativeActiveEnergy                         : Number,      
    DCch4Current                                      : Number,      
    DCch4ActivePower                                  : Number,      
    DCch4CombinedActiveEnergy                         : Number,      
    DCch4PositiveActiveEnergy                         : Number,      
    DCch4NegativeActiveEnergy                         : Number,      
    DCch5Current                                      : Number,      
    DCch5ActivePower                                  : Number,      
    DCch5CombinedActiveEnergy                         : Number,      
    DCch5PositiveActiveEnergy                         : Number,      
    DCch5NegativeActiveEnergy                         : Number,      
    DCch6Current                                      : Number,      
    DCch6ActivePower                                  : Number,      
    DCch6CombinedActiveEnergy                         : Number,      
    DCch6PositiveActiveEnergy                         : Number,      
    DCch6NegativeActiveEnergy                         : Number,
    ACSourceTotalPowerDownTime                        : Number, 
    ACelectricalMeterFailureAlarm                     : Number, 
    AC1stElectParamMeasureNormal                      : Number, 
    AC1stVoltagePhaseSequenceErr                      : Number, 
    AC1stCurrentPhaseSequenceErr                      : Number,
    outSideTemp                                       : Number, 
    outSideHumi                                       : Number, 
    batTemp                                           : Number, 
    sysVolt                                           : Number, 
    th22Failed                                        : Number,
    lm35Failed                                        : Number,
    digitalIn1                                        : Number,
    digitalIn2                                        : Number,
    digitalIn3                                        : Number,
    digitalIn4                                        : Number,
    digitalOut1                                       : Number,
    digitalOut2                                       : Number,
    digitalOut3                                       : Number,
    digitalOut4                                       : Number,  
    comConnected                                      : Boolean, 
    internet                                          : Boolean,    

    createdAt: {type: Date, default: Date.now}
},{
    capped: { size: 100, max: 3500}
});
// OperationData.plugin(passportLocalMongoose);

module.exports = mongoose.model("BufferedOperationData", BufferedOperationDataSchema);



                    